apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: npapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npapp
  template:
    metadata:
      labels:
        app: npapp 
    spec:
      containers:
      - name: myapp-cont
        image: nginx:latest
        ports:
        - containerPort: 80

